version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
      POSTGRES_DB: bankdb
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: bankuser
      DB_PASSWORD: bankpass
      DB_NAME: bankdb
      JWT_SECRET: super-secret-key
      JWT_TTL: 24h