name: Build and Test Bank API

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
      - name: Install dependencies
        run: |
          go mod tidy
          go get github.com/stretchr/testify
          go get github.com/golang-jwt/jwt/v5
      - name: Run unit tests
        run: go test ./services -v